backend:
  name: github
  repo: theadell/blog 
  branch: main
  base_url: https://decap.adelhub.com

media_folder: "static/images/uploads"
collections:
  - name: "Timeline Entries" # Identifier for the collection
    label: "Timeline Entries" # Display name in the CMS
    folder: "content/timeline" # Path to the folder containing timeline files
    create: true # Allow creating new posts
    slug: "{{slug}}" # Template for generating post slugs (file names)
    extension: "md" # File extension for the markdown files
    format: "toml-frontmatter" # Specifies the TOML front matter format
    frontmatter_delimiter: "+++" # Delimiter for the TOML front matter
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DDTHH:mm:ssZ" 
        date_format: "YYYY-MM-DD" 
        time_format: "HH:mm:ss" 
        picker_utc: true 
      - label: "Draft"
        name: "draft"
        widget: "boolean"
      - label: "Author Name"
        name: "author"
        widget: "string"
      - label: "Class or Topic Name"
        name: "class"
        widget: "string"
      - label: "Body"
        name: "body"
        widget: "markdown"


